### ISSUE TITLE
大佬还能用吗

### ISSUE THREAD

**Issue by yumu7777777** [gengjian1203/wechatShareCard#1]

**Comment by gengjian1203** [comment]
em.....有点年代久远忘记了。不过微信分享卡片蛮简单，配置几个微信api，然后从几个固定入口发出就可以用的。
可以参考这两个连接：
https://www.orz2.top/gengjian1203/2022/05/24/36-%E8%B0%83%E7%A0%94%E5%BE%AE%E4%BF%A1%E9%93%BE%E6%8E%A5%E5%8D%A1%E7%89%87%E5%88%86%E4%BA%AB%E6%80%BB%E7%BB%93/

https://blog.csdn.net/weixin_44646763/article/details/120689669

**Comment by yumu7777777** [comment]
好的好的，这种好像必须用户在微信手动分享才行，我这边想的是通过程序往群里发卡片，难搞
